package org.omg.IOP;


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/mesos/slaves/9190d864-6621-4810-ba08-d8d8c75ba674-S34/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/f87b4890-2412-429e-bdfd-83788a246cfb/runs/8f4f187f-165d-4027-8162-c5cc52d7c3d8/workspace/open/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, June 28, 2018 at 12:47:39 AM Greenwich Mean Time
*/

public interface CodeSets
{

  /**
       * Identifies a CDR encapsulation of the 
       * <code>CONV_FRAME.CodeSetContext</code> defined in 
       * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
       */
  public static final int value = (int)(1L);
}
