package org.omg.IOP;


/**
* org/omg/IOP/ExceptionDetailMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/mesos/slaves/9190d864-6621-4810-ba08-d8d8c75ba674-S34/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/f87b4890-2412-429e-bdfd-83788a246cfb/runs/8f4f187f-165d-4027-8162-c5cc52d7c3d8/workspace/open/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, June 28, 2018 at 12:47:39 AM Greenwich Mean Time
*/

public interface ExceptionDetailMessage
{

  /**
       * CORBA formal/02-06-01: 13.7.1:
       * ExceptionDetailMessage identifies a CDR encapsulation of a wstring,
       * encoded using GIOP 1.2 with a TCS-W of UTF-16.  This service context
       * may be sent on Reply messages with a reply_status of SYSTEM_EXCEPTION
       * or USER_EXCEPTION. The usage of this service context is defined
       * by language mappings. <br> <br>
       *
       * IDL/Java: ptc/02-01-22: 1.15.2: 
       * When a System Exception is marshaled, its GIOP Reply message shall
       * include an associated ExceptionDetailMessage service context. The
       * callee's stack trace is often very valuable debugging information but
       * may contain sensitive or unwanted information. The wstring within the
       * service context will therefore contain additional information relating
       * to the exception, for example the result of calling either
       * printStackTrace(PrintWriter) or getMessage() on the exception. When
       * unmarshaling a System Exception on the client side, the wstring from
       * any ExceptionDetailMessage service context shall become the Java error
       * message in the unmarshaled exception object.
       */
  public static final int value = (int)(14L);
}
