package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/mesos/slaves/9190d864-6621-4810-ba08-d8d8c75ba674-S34/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/f87b4890-2412-429e-bdfd-83788a246cfb/runs/8f4f187f-165d-4027-8162-c5cc52d7c3d8/workspace/open/src/java.corba/share/classes/org/omg/PortableInterceptor/IOP.idl
* Thursday, June 28, 2018 at 12:47:39 AM Greenwich Mean Time
*/

public interface RMICustomMaxStreamFormat
{

  /**
       * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
       * service context which contains a single byte specifying
       * the client's maximum RMI-IIOP stream format version.
       *
       * See Java to IDL ptc/02-01-12 1.4.12.
       */
  public static final int value = (int)(17L);
}
