package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/IORInterceptorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /scratch/mesos/slaves/9190d864-6621-4810-ba08-d8d8c75ba674-S34/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/f87b4890-2412-429e-bdfd-83788a246cfb/runs/8f4f187f-165d-4027-8162-c5cc52d7c3d8/workspace/open/src/java.corba/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Thursday, June 28, 2018 at 12:47:39 AM Greenwich Mean Time
*/


/**
   * Interceptor used to establish tagged components in the profiles within 
   * an IOR.
   * <p>
   * In some cases, a portable ORB service implementation may need to add 
   * information describing the server's or object's ORB service related 
   * capabilities to object references in order to enable the ORB service 
   * implementation in the client to function properly. 
   * <p>
   * This is supported through the <code>IORInterceptor</code> and 
   * <code>IORInfo</code> interfaces. 
   *
   * @see IORInfo
   */
public interface IORInterceptorOperations  extends org.omg.PortableInterceptor.InterceptorOperations
{

  /**
       * A server side ORB calls the <code>establish_components</code> 
       * operation on all registered <code>IORInterceptor</code> instances 
       * when it is assembling the list of components that will be included 
       * in the profile or profiles of an object reference. This operation 
       * is not necessarily called for each individual object reference. 
       * In the case of the POA, this operation is called each time POA::create_POA
       * is called.  In any case, <code>establish_components</code> is 
       * guaranteed to be called at least once for each distinct set of 
       * server policies. 
       * <p>
       * An implementation of <code>establish_components</code> must not 
       * throw exceptions. If it does, the ORB shall ignore the exception 
       * and proceed to call the next IOR Interceptor's 
       * <code>establish_components</code> operation. 
       *
       * @param info The <code>IORInfo</code> instance used by the ORB 
       *     service to query applicable policies and add components to be 
       *     included in the generated IORs.
       */
  void establish_components (org.omg.PortableInterceptor.IORInfo info);
} // interface IORInterceptorOperations
